Document: info6005cw1cs3e11
Title: Debian info6005cw1cs3e11 Manual
Author: <insert document author here>
Abstract: This manual describes what info6005cw1cs3e11 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/info6005cw1cs3e11/info6005cw1cs3e11.sgml.gz

Format: postscript
Files: /usr/share/doc/info6005cw1cs3e11/info6005cw1cs3e11.ps.gz

Format: text
Files: /usr/share/doc/info6005cw1cs3e11/info6005cw1cs3e11.text.gz

Format: HTML
Index: /usr/share/doc/info6005cw1cs3e11/html/index.html
Files: /usr/share/doc/info6005cw1cs3e11/html/*.html
